import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import HomeComp from "@/components/homeComp/HomeComp";
import { carsData } from "../../carsData";
import { useEffect, useState } from "react";
import LayOut from "@/components/layout/LayOut";
if (typeof window !== "undefined") {
  require("bootstrap/dist/js/bootstrap.bundle");
}

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [Searchkey, setSearchkey] = useState("");
  const [priceRange, setPriceRange] = useState<string[]>(["110000"]);
  const [itemsCount, setItemsCount] = useState(carsData.length);
  const [Cars, setCars] = useState(carsData);


console.log(priceRange)
  const handleSearch = (searchTerm: any) => {
    const term = searchTerm.toLowerCase();
    setSearchkey(term);

    if (term.length > 2) {
      const filtered = carsData.filter(
        (car) =>
          car.Title.toLowerCase().includes(term) ||
          car.Category.toLowerCase().includes(term)
      );

      const sorted = [...filtered].sort((a, b) =>
        a.Title.localeCompare(b.Title)
      );
      setCars(sorted);
      setItemsCount(filtered.length !== 0 ? filtered.length : carsData.length);
    }
  };

  useEffect(() => {
    if (Searchkey !== "") {
      handleSearch(Searchkey);
    } else {
      setCars(carsData);
      setItemsCount(carsData.length);
    }
  }, [Searchkey]);


  return (
    <>
      <Head>
        <title>Vechicles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <LayOut
          setSearchkey={setSearchkey}
          Searchkey={Searchkey}
          itemsCount={itemsCount}
          priceRange={priceRange}
          setPriceRange={setPriceRange}
        >
          <HomeComp carsData={Cars.length !== 0 ? Cars : carsData} />
        </LayOut>
      </main>
    </>
  );
}
