import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import HomeComp from "@/components/homeComp/HomeComp";
import { carsData } from "../../carsData";
import { ChangeEvent, useEffect, useState } from "react";
import LayOut from "@/components/layout/LayOut";
import { useRouter } from "next/router";
if (typeof window !== "undefined") {
  require("bootstrap/dist/js/bootstrap.bundle");
}

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const { query } = router;

  const [itemsCount, setItemsCount] = useState(carsData.length);
  const [Cars, setCars] = useState(carsData);

  const handleSearch = (searchTerm: any) => {
    const term = searchTerm.toLowerCase();
    if (term.length > 2) {
      const filtered = carsData.filter(
        (car) =>
          car.Title.toLowerCase().includes(term) ||
          car.Category.toLowerCase().includes(term)
      );

      const sortedByDesc = [...filtered].sort((a:any, b:any) => {
        return query?.orderby === "price" ? a.CurrentPriceStr.localeCompare(b.CurrentPriceStr)  : b.FilterEndDateStr.localeCompare(a.FilterEndDateStr);
      });
      console.log(sortedByDesc)
      const sorted = [...filtered].sort((a, b) =>
        a.Title.localeCompare(b.Title)
      );
      
      setCars(sortedByDesc);
      setItemsCount(filtered.length !== 0 ? filtered.length : carsData.length);
    }
  };
 
  useEffect(() => {
    const lengthQ:number = Number(query?.q?.length);
    if (lengthQ > 2 ) {
      handleSearch(query?.q);
    } else {
      setCars(carsData);
      setItemsCount(carsData.length);
    }
  }, [query]);


  return (
    <>
      <Head>
        <title>Vechicles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <LayOut
          itemsCount={itemsCount}
        >
          <HomeComp carsData={Cars.length !== 0 ? Cars : carsData}/>
        </LayOut>
      </main>
    </>
  );
}
